server = "https://registry.domain.com:5000"

[host."https://registry.domain.com:5000"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
  #ca = "/path/to/ocicrypt-pqc-provider/example/certs/tls-ca-chain.pem"
